### ISSUE TITLE
Popup is opened when the icon is dragged

### ISSUE THREAD

**Issue by secit-pl** [inket/MBPopup#3]
When we click on icon holding down the command button to drag it the popup is opened as a normal click do. 

![bug](https://user-images.githubusercontent.com/24696884/73433022-35f04f80-4344-11ea-893d-4493cd50118f.gif)

**Comment by inket** [comment]
Hey! Thanks for sharing this issue. I fixed it in 5.0.2, should be all good now 👍

**Comment by secit-pl** [comment]
Works perfectly, thanks!
