### ISSUE TITLE
How to prevent popup opening when holding option key?

### ISSUE THREAD

**Issue by secit-pl** [inket/MBPopup#4]
Is there a possibility to prevent popup opening if the menu bar icon was clicked while holding option key?
I have found the way how to detect if the option key was used but I cannot prevent popup from being opened.

```swift
popupController.willOpenPopup = {
    keys in debugPrint("Will open popup!")
    
    if (keys == .option) {
        self.popupController.close() // doesn't work
    }
}
```

**Comment by inket** [comment]
I'll have to add a new callback where you can return a bool to decide whether you want it to open or not

**Comment by inket** [comment]
See https://github.com/inket/MBPopup/commit/7f8d6f31f411e8fb1c26c90ffe526fea3a01fc3c for usage!

**Comment by secit-pl** [comment]
@inket works like charm. Thanks for your marvelous support!
